model:
  chemical_species:
  - Mo
  - S
  cutoff: 5.0
  channel: 32
  lmax: 2
  num_convolution_layer: 3
  weight_nn_hidden_neurons:
  - 64
  - 64
  radial_basis:
    radial_basis_name: bessel
    bessel_basis_num: 8
  cutoff_function:
    cutoff_function_name: poly_cut
    poly_cut_p_value: 6
  act_gate:
    e: silu
    o: tanh
  act_scalar:
    e: silu
    o: tanh
  is_parity: false
  self_connection_type: linear
  interaction_type: nequip
  conv_denominator: avg_num_neigh
  train_denominator: false
  train_shift_scale: false
train:
  random_seed: 3278
  train_shuffle: true
  is_train_stress: true
  epoch: 456
  per_epoch: 20
  optimizer: adam
  optim_param:
    lr: 0.0004
  scheduler: linearlr
  scheduler_param:
    start_factor: 1.0
    total_iters: 456
    end_factor: 1.0e-07
  force_loss_weight: 1.0
  stress_loss_weight: 0.001
  error_record:
  - - Energy
    - RMSE
  - - Force
    - RMSE
  - - Stress
    - RMSE
  - - Energy
    - Loss
  - - Force
    - Loss
  - - Stress
    - Loss
  - - TotalLoss
    - None
  best_metric: TotalLoss
data:
  batch_size: 210
  shift: per_atom_energy_mean
  scale: force_rms
  data_format: ase
  data_format_args:
    energy_key: ref_energy
    force_key: ref_forces
    stress_key: ref_stress
  load_trainset_path:
  - ../copied_data/sevenn_data/graph_trainset.pt
  load_validset_path:
  - ../copied_data/sevenn_data/graph_validset.pt
